drop policy "Enable insert for authenticated users only" on "public"."post_categories";

drop policy "Enable read access for all users" on "public"."post_categories";

drop policy "Enable update for authenticated users only" on "public"."post_categories";

alter table "public"."post_categories" drop constraint "post_categories_slug_key";

alter table "public"."post_sections" drop constraint "post_sections_category_id_fkey";

alter table "public"."posts" drop constraint "posts_category_id_fkey";

alter table "public"."post_categories" drop constraint "post_categories_pkey";

drop index if exists "public"."post_categories_pkey";

drop index if exists "public"."post_categories_slug_key";

create table "public"."categories" (
    "id" bigint generated always as identity not null,
    "name" text not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "slug" text not null
);


alter table "public"."categories" enable row level security;

create table "public"."category-relations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "parent_category_id" bigint,
    "child_category_id" bigint
);


alter table "public"."category-relations" enable row level security;

alter table "public"."post_categories" drop column "name";

alter table "public"."post_categories" drop column "slug";

alter table "public"."post_categories" add column "category_id" bigint;

alter table "public"."post_categories" add column "post_id" bigint;

alter table "public"."post_categories" alter column "created_at" set default now();

alter table "public"."post_categories" alter column "id" set generated by default;

CREATE UNIQUE INDEX "category-relations_pkey" ON public."category-relations" USING btree (id);

CREATE UNIQUE INDEX post_categories_pkey1 ON public.post_categories USING btree (id);

CREATE UNIQUE INDEX post_categories_pkey ON public.categories USING btree (id);

CREATE UNIQUE INDEX post_categories_slug_key ON public.categories USING btree (slug);

alter table "public"."categories" add constraint "post_categories_pkey" PRIMARY KEY using index "post_categories_pkey";

alter table "public"."category-relations" add constraint "category-relations_pkey" PRIMARY KEY using index "category-relations_pkey";

alter table "public"."post_categories" add constraint "post_categories_pkey1" PRIMARY KEY using index "post_categories_pkey1";

alter table "public"."categories" add constraint "post_categories_slug_key" UNIQUE using index "post_categories_slug_key";

alter table "public"."category-relations" add constraint "category-relations_child_category_id_fkey" FOREIGN KEY (child_category_id) REFERENCES categories(id) not valid;

alter table "public"."category-relations" validate constraint "category-relations_child_category_id_fkey";

alter table "public"."category-relations" add constraint "category-relations_parent_category_id_fkey" FOREIGN KEY (parent_category_id) REFERENCES categories(id) not valid;

alter table "public"."category-relations" validate constraint "category-relations_parent_category_id_fkey";

alter table "public"."post_categories" add constraint "post_categories_category_id_fkey" FOREIGN KEY (category_id) REFERENCES categories(id) not valid;

alter table "public"."post_categories" validate constraint "post_categories_category_id_fkey";

alter table "public"."post_categories" add constraint "post_categories_post_id_fkey" FOREIGN KEY (post_id) REFERENCES posts(id) not valid;

alter table "public"."post_categories" validate constraint "post_categories_post_id_fkey";

alter table "public"."post_sections" add constraint "post_sections_category_id_fkey" FOREIGN KEY (category_id) REFERENCES categories(id) not valid;

alter table "public"."post_sections" validate constraint "post_sections_category_id_fkey";

alter table "public"."posts" add constraint "posts_category_id_fkey" FOREIGN KEY (category_id) REFERENCES categories(id) not valid;

alter table "public"."posts" validate constraint "posts_category_id_fkey";

grant delete on table "public"."categories" to "anon";

grant insert on table "public"."categories" to "anon";

grant references on table "public"."categories" to "anon";

grant select on table "public"."categories" to "anon";

grant trigger on table "public"."categories" to "anon";

grant truncate on table "public"."categories" to "anon";

grant update on table "public"."categories" to "anon";

grant delete on table "public"."categories" to "authenticated";

grant insert on table "public"."categories" to "authenticated";

grant references on table "public"."categories" to "authenticated";

grant select on table "public"."categories" to "authenticated";

grant trigger on table "public"."categories" to "authenticated";

grant truncate on table "public"."categories" to "authenticated";

grant update on table "public"."categories" to "authenticated";

grant delete on table "public"."categories" to "service_role";

grant insert on table "public"."categories" to "service_role";

grant references on table "public"."categories" to "service_role";

grant select on table "public"."categories" to "service_role";

grant trigger on table "public"."categories" to "service_role";

grant truncate on table "public"."categories" to "service_role";

grant update on table "public"."categories" to "service_role";

grant delete on table "public"."category-relations" to "anon";

grant insert on table "public"."category-relations" to "anon";

grant references on table "public"."category-relations" to "anon";

grant select on table "public"."category-relations" to "anon";

grant trigger on table "public"."category-relations" to "anon";

grant truncate on table "public"."category-relations" to "anon";

grant update on table "public"."category-relations" to "anon";

grant delete on table "public"."category-relations" to "authenticated";

grant insert on table "public"."category-relations" to "authenticated";

grant references on table "public"."category-relations" to "authenticated";

grant select on table "public"."category-relations" to "authenticated";

grant trigger on table "public"."category-relations" to "authenticated";

grant truncate on table "public"."category-relations" to "authenticated";

grant update on table "public"."category-relations" to "authenticated";

grant delete on table "public"."category-relations" to "service_role";

grant insert on table "public"."category-relations" to "service_role";

grant references on table "public"."category-relations" to "service_role";

grant select on table "public"."category-relations" to "service_role";

grant trigger on table "public"."category-relations" to "service_role";

grant truncate on table "public"."category-relations" to "service_role";

grant update on table "public"."category-relations" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."categories"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."categories"
as permissive
for select
to public
using (true);


create policy "Enable update for authenticated users only"
on "public"."categories"
as permissive
for update
to authenticated
with check (true);



