alter table "public"."tags" drop constraint "tags_tag_key";

drop index if exists "public"."tags_tag_key";

create table "public"."post_section_references" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "source_post_section_id" bigint,
    "destination_post_section_id" bigint
);


alter table "public"."post_section_references" enable row level security;

alter table "public"."post_categories" add column "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text);

alter table "public"."post_categories" add column "slug" text not null;

alter table "public"."post_comments" drop column "section_order";

alter table "public"."post_comments" add column "external_reference_url" text;

alter table "public"."post_sections" add column "external_reference_url" text;

alter table "public"."posts" add column "thumbnail_url" text;

alter table "public"."tags" drop column "tag";

alter table "public"."tags" add column "name" text not null;

alter table "public"."tags" add column "slug" text not null;

alter table "public"."teams" add column "slug" text not null;

CREATE UNIQUE INDEX post_categories_slug_key ON public.post_categories USING btree (slug);

CREATE UNIQUE INDEX post_section_references_pkey ON public.post_section_references USING btree (id);

CREATE UNIQUE INDEX tags_slug_key ON public.tags USING btree (slug);

CREATE UNIQUE INDEX teams_slug_key ON public.teams USING btree (slug);

CREATE UNIQUE INDEX tags_tag_key ON public.tags USING btree (name);

alter table "public"."post_section_references" add constraint "post_section_references_pkey" PRIMARY KEY using index "post_section_references_pkey";

alter table "public"."post_categories" add constraint "post_categories_slug_key" UNIQUE using index "post_categories_slug_key";

alter table "public"."tags" add constraint "tags_slug_key" UNIQUE using index "tags_slug_key";

alter table "public"."teams" add constraint "teams_slug_key" UNIQUE using index "teams_slug_key";

alter table "public"."tags" add constraint "tags_tag_key" UNIQUE using index "tags_tag_key";

grant delete on table "public"."post_section_references" to "anon";

grant insert on table "public"."post_section_references" to "anon";

grant references on table "public"."post_section_references" to "anon";

grant select on table "public"."post_section_references" to "anon";

grant trigger on table "public"."post_section_references" to "anon";

grant truncate on table "public"."post_section_references" to "anon";

grant update on table "public"."post_section_references" to "anon";

grant delete on table "public"."post_section_references" to "authenticated";

grant insert on table "public"."post_section_references" to "authenticated";

grant references on table "public"."post_section_references" to "authenticated";

grant select on table "public"."post_section_references" to "authenticated";

grant trigger on table "public"."post_section_references" to "authenticated";

grant truncate on table "public"."post_section_references" to "authenticated";

grant update on table "public"."post_section_references" to "authenticated";

grant delete on table "public"."post_section_references" to "service_role";

grant insert on table "public"."post_section_references" to "service_role";

grant references on table "public"."post_section_references" to "service_role";

grant select on table "public"."post_section_references" to "service_role";

grant trigger on table "public"."post_section_references" to "service_role";

grant truncate on table "public"."post_section_references" to "service_role";

grant update on table "public"."post_section_references" to "service_role";


