create table "public"."postsecion_tags" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "post_section_id" bigint not null,
    "tag_id" bigint not null
);


alter table "public"."postsecion_tags" enable row level security;

alter table "public"."post_sections" add column "category_id" bigint;

CREATE UNIQUE INDEX posts_slug_key ON public.posts USING btree (slug);

CREATE UNIQUE INDEX postsecion_tags_pkey ON public.postsecion_tags USING btree (id);

alter table "public"."postsecion_tags" add constraint "postsecion_tags_pkey" PRIMARY KEY using index "postsecion_tags_pkey";

alter table "public"."post_sections" add constraint "post_sections_category_id_fkey" FOREIGN KEY (category_id) REFERENCES post_categories(id) not valid;

alter table "public"."post_sections" validate constraint "post_sections_category_id_fkey";

alter table "public"."posts" add constraint "posts_slug_key" UNIQUE using index "posts_slug_key";

alter table "public"."postsecion_tags" add constraint "postsecion_tags_post_section_id_fkey" FOREIGN KEY (post_section_id) REFERENCES post_sections(id) not valid;

alter table "public"."postsecion_tags" validate constraint "postsecion_tags_post_section_id_fkey";

alter table "public"."postsecion_tags" add constraint "postsecion_tags_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES tags(id) not valid;

alter table "public"."postsecion_tags" validate constraint "postsecion_tags_tag_id_fkey";

grant delete on table "public"."postsecion_tags" to "anon";

grant insert on table "public"."postsecion_tags" to "anon";

grant references on table "public"."postsecion_tags" to "anon";

grant select on table "public"."postsecion_tags" to "anon";

grant trigger on table "public"."postsecion_tags" to "anon";

grant truncate on table "public"."postsecion_tags" to "anon";

grant update on table "public"."postsecion_tags" to "anon";

grant delete on table "public"."postsecion_tags" to "authenticated";

grant insert on table "public"."postsecion_tags" to "authenticated";

grant references on table "public"."postsecion_tags" to "authenticated";

grant select on table "public"."postsecion_tags" to "authenticated";

grant trigger on table "public"."postsecion_tags" to "authenticated";

grant truncate on table "public"."postsecion_tags" to "authenticated";

grant update on table "public"."postsecion_tags" to "authenticated";

grant delete on table "public"."postsecion_tags" to "service_role";

grant insert on table "public"."postsecion_tags" to "service_role";

grant references on table "public"."postsecion_tags" to "service_role";

grant select on table "public"."postsecion_tags" to "service_role";

grant trigger on table "public"."postsecion_tags" to "service_role";

grant truncate on table "public"."postsecion_tags" to "service_role";

grant update on table "public"."postsecion_tags" to "service_role";


