revoke delete on table "public"."category-relations" from "anon";

revoke insert on table "public"."category-relations" from "anon";

revoke references on table "public"."category-relations" from "anon";

revoke select on table "public"."category-relations" from "anon";

revoke trigger on table "public"."category-relations" from "anon";

revoke truncate on table "public"."category-relations" from "anon";

revoke update on table "public"."category-relations" from "anon";

revoke delete on table "public"."category-relations" from "authenticated";

revoke insert on table "public"."category-relations" from "authenticated";

revoke references on table "public"."category-relations" from "authenticated";

revoke select on table "public"."category-relations" from "authenticated";

revoke trigger on table "public"."category-relations" from "authenticated";

revoke truncate on table "public"."category-relations" from "authenticated";

revoke update on table "public"."category-relations" from "authenticated";

revoke delete on table "public"."category-relations" from "service_role";

revoke insert on table "public"."category-relations" from "service_role";

revoke references on table "public"."category-relations" from "service_role";

revoke select on table "public"."category-relations" from "service_role";

revoke trigger on table "public"."category-relations" from "service_role";

revoke truncate on table "public"."category-relations" from "service_role";

revoke update on table "public"."category-relations" from "service_role";

alter table "public"."category-relations" drop constraint "category-relations_child_category_id_fkey";

alter table "public"."category-relations" drop constraint "category-relations_parent_category_id_fkey";

alter table "public"."post_sections" drop constraint "post_sections_category_id_fkey";

alter table "public"."category-relations" drop constraint "category-relations_pkey";

drop index if exists "public"."category-relations_pkey";

drop table "public"."category-relations";

create table "public"."category_relations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "parent_category_id" bigint,
    "child_category_id" bigint
);


alter table "public"."category_relations" enable row level security;

create table "public"."post_section_categories" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "category_id" bigint,
    "post_section_id" bigint
);


alter table "public"."post_section_categories" enable row level security;

alter table "public"."post_sections" drop column "category_id";

CREATE UNIQUE INDEX post_section_categories_pkey ON public.post_section_categories USING btree (id);

CREATE UNIQUE INDEX "category-relations_pkey" ON public.category_relations USING btree (id);

alter table "public"."category_relations" add constraint "category-relations_pkey" PRIMARY KEY using index "category-relations_pkey";

alter table "public"."post_section_categories" add constraint "post_section_categories_pkey" PRIMARY KEY using index "post_section_categories_pkey";

alter table "public"."category_relations" add constraint "category_relations_child_category_id_fkey" FOREIGN KEY (child_category_id) REFERENCES categories(id) not valid;

alter table "public"."category_relations" validate constraint "category_relations_child_category_id_fkey";

alter table "public"."category_relations" add constraint "category_relations_parent_category_id_fkey" FOREIGN KEY (parent_category_id) REFERENCES categories(id) not valid;

alter table "public"."category_relations" validate constraint "category_relations_parent_category_id_fkey";

alter table "public"."post_section_categories" add constraint "post_section_categories_category_id_fkey" FOREIGN KEY (category_id) REFERENCES categories(id) not valid;

alter table "public"."post_section_categories" validate constraint "post_section_categories_category_id_fkey";

alter table "public"."post_section_categories" add constraint "post_section_categories_post_section_id_fkey" FOREIGN KEY (post_section_id) REFERENCES post_sections(id) not valid;

alter table "public"."post_section_categories" validate constraint "post_section_categories_post_section_id_fkey";

grant delete on table "public"."category_relations" to "anon";

grant insert on table "public"."category_relations" to "anon";

grant references on table "public"."category_relations" to "anon";

grant select on table "public"."category_relations" to "anon";

grant trigger on table "public"."category_relations" to "anon";

grant truncate on table "public"."category_relations" to "anon";

grant update on table "public"."category_relations" to "anon";

grant delete on table "public"."category_relations" to "authenticated";

grant insert on table "public"."category_relations" to "authenticated";

grant references on table "public"."category_relations" to "authenticated";

grant select on table "public"."category_relations" to "authenticated";

grant trigger on table "public"."category_relations" to "authenticated";

grant truncate on table "public"."category_relations" to "authenticated";

grant update on table "public"."category_relations" to "authenticated";

grant delete on table "public"."category_relations" to "service_role";

grant insert on table "public"."category_relations" to "service_role";

grant references on table "public"."category_relations" to "service_role";

grant select on table "public"."category_relations" to "service_role";

grant trigger on table "public"."category_relations" to "service_role";

grant truncate on table "public"."category_relations" to "service_role";

grant update on table "public"."category_relations" to "service_role";

grant delete on table "public"."post_section_categories" to "anon";

grant insert on table "public"."post_section_categories" to "anon";

grant references on table "public"."post_section_categories" to "anon";

grant select on table "public"."post_section_categories" to "anon";

grant trigger on table "public"."post_section_categories" to "anon";

grant truncate on table "public"."post_section_categories" to "anon";

grant update on table "public"."post_section_categories" to "anon";

grant delete on table "public"."post_section_categories" to "authenticated";

grant insert on table "public"."post_section_categories" to "authenticated";

grant references on table "public"."post_section_categories" to "authenticated";

grant select on table "public"."post_section_categories" to "authenticated";

grant trigger on table "public"."post_section_categories" to "authenticated";

grant truncate on table "public"."post_section_categories" to "authenticated";

grant update on table "public"."post_section_categories" to "authenticated";

grant delete on table "public"."post_section_categories" to "service_role";

grant insert on table "public"."post_section_categories" to "service_role";

grant references on table "public"."post_section_categories" to "service_role";

grant select on table "public"."post_section_categories" to "service_role";

grant trigger on table "public"."post_section_categories" to "service_role";

grant truncate on table "public"."post_section_categories" to "service_role";

grant update on table "public"."post_section_categories" to "service_role";


