alter table "public"."post_categories" drop constraint "post_categories_category_id_fkey";

alter table "public"."post_categories" drop constraint "post_categories_post_id_fkey";

create table "public"."post_series" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "thumbnail_url" text,
    "slug" text not null
);


alter table "public"."post_series" enable row level security;

alter table "public"."posts" add column "series_id" bigint;

CREATE UNIQUE INDEX post_series_pkey ON public.post_series USING btree (id);

CREATE UNIQUE INDEX post_series_slug_key ON public.post_series USING btree (slug);

alter table "public"."post_series" add constraint "post_series_pkey" PRIMARY KEY using index "post_series_pkey";

alter table "public"."post_series" add constraint "post_series_slug_key" UNIQUE using index "post_series_slug_key";

alter table "public"."posts" add constraint "posts_series_id_fkey" FOREIGN KEY (series_id) REFERENCES post_series(id) ON DELETE SET NULL not valid;

alter table "public"."posts" validate constraint "posts_series_id_fkey";

alter table "public"."post_categories" add constraint "post_categories_category_id_fkey" FOREIGN KEY (category_id) REFERENCES categories(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."post_categories" validate constraint "post_categories_category_id_fkey";

alter table "public"."post_categories" add constraint "post_categories_post_id_fkey" FOREIGN KEY (post_id) REFERENCES posts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."post_categories" validate constraint "post_categories_post_id_fkey";

grant delete on table "public"."post_series" to "anon";

grant insert on table "public"."post_series" to "anon";

grant references on table "public"."post_series" to "anon";

grant select on table "public"."post_series" to "anon";

grant trigger on table "public"."post_series" to "anon";

grant truncate on table "public"."post_series" to "anon";

grant update on table "public"."post_series" to "anon";

grant delete on table "public"."post_series" to "authenticated";

grant insert on table "public"."post_series" to "authenticated";

grant references on table "public"."post_series" to "authenticated";

grant select on table "public"."post_series" to "authenticated";

grant trigger on table "public"."post_series" to "authenticated";

grant truncate on table "public"."post_series" to "authenticated";

grant update on table "public"."post_series" to "authenticated";

grant delete on table "public"."post_series" to "service_role";

grant insert on table "public"."post_series" to "service_role";

grant references on table "public"."post_series" to "service_role";

grant select on table "public"."post_series" to "service_role";

grant trigger on table "public"."post_series" to "service_role";

grant truncate on table "public"."post_series" to "service_role";

grant update on table "public"."post_series" to "service_role";


